### ISSUE TITLE
Dataset Version

### ISSUE THREAD

**Issue by zahir-w** [CMURoboTouch/PoseIt#2]
Hi, it's a really wonderful work. I am wondering if there is a lite dataset version to download or the split zip dataset? It seems the gelsight dataset is too larger (800GB+). Many Thanks!

**Comment by arpit15** [comment]
I am not aware of any toy version of this dataset. I will check in the lab if we can share something small for you. Ping here again in a week if I don't respond on this.

**Comment by zahir-w** [comment]
Oh, thanks a lot!

**Comment by zahir-w** [comment]
Hi, is there something small to share? Thanks.

> I am not aware of any toy version of this dataset. I will check in the lab if we can share something small for you. Ping here again in a week if I don't respond on this.

**Comment by rhzhang-ustc** [comment]
> Hi, is there something small to share? Thanks.
> 
> > I am not aware of any toy version of this dataset. I will check in the lab if we can share something small for you. Ping here again in a week if I don't respond on this.

Hi, I'm a student that also uses this dataset. I can share with you a smaller version that I use (~100G).  Can you wait for another day? I'm packing things up.

**Comment by zahir-w** [comment]
> > Hi, is there something small to share? Thanks.
> > > I am not aware of any toy version of this dataset. I will check in the lab if we can share something small for you. Ping here again in a week if I don't respond on this.
> 
> Hi, I'm a student that also uses this dataset. I can share with you a smaller version that I use (~100G). Can you wait for another day? I'm packing things up.

Ok, thank you! This shall help me a lot!

**Comment by rhzhang-ustc** [comment]
Hi, please check this link:
https://drive.google.com/file/d/1nRR2-GOhmePqmKrzRKloOenIbu5NB0_1/view?usp=drive_link

**Comment by zahir-w** [comment]
> Hi, please check this link:
> https://drive.google.com/file/d/1nRR2-GOhmePqmKrzRKloOenIbu5NB0_1/view?usp=drive_link

Wow, Thanks!!! I will download it later.
